version: '3.1'
services:
  api:
    container_name: senac-1
    build: .
    ports:
      -${API_PORT}:${API_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - postgres

  postgres:
    container_name: bd-senac-postgressql1
    image: 'postgres:13-alpine'
    ports:
      - '${TYPEORM_PORT}:${TYPEORM_PORT}'
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    networks:
      - docker-network
networks:
  docker-network: