version: '3.7'
services:
  api:
    container_name: senac-1
    build: .
    ports: ["3000:3000"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - postgres

  postgres:
    container_name: bd-senac-postgressql1
    image: 'postgres:13-alpine'
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - docker-network
networks:
  docker-network: